M.Talha Ramzan
---
2330-0141
---
BS AI
---
LAb 05
---
Machine Learning
---

**Libraries Import**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

**Dataset Load**

In [2]:
df = pd.read_excel("Iris.xlsx")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

**Dataset Info**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

**Check Missing Values**

In [4]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

**Id Column Remove**

In [5]:
df = df.drop("Id", axis=1)
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

**Features aur Target Separate**

In [6]:
X = df.drop("Species", axis=1)
y = df["Species"]

**Task 1 — SVM with 2 Features**

In [8]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# 2 features select
X2 = df[['SepalLengthCm', 'SepalWidthCm']]
y = df['Species']

# split
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y, test_size=0.2, random_state=42)

# model
svm_2 = SVC(kernel='linear')

svm_2.fit(X_train2, y_train2)

# prediction
pred2 = svm_2.predict(X_test2)

# accuracy
acc2 = accuracy_score(y_test2, pred2)

print("Accuracy with 2 features:", acc2)

Accuracy with 2 features: 0.9

**Task 2 — SVM with 4 Features**

In [9]:
X4 = df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = df['Species']

X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y, test_size=0.2, random_state=42)

svm_4 = SVC(kernel='linear')

svm_4.fit(X_train4, y_train4)

pred4 = svm_4.predict(X_test4)

acc4 = accuracy_score(y_test4, pred4)

print("Accuracy with 4 features:", acc4)

Accuracy with 4 features: 1.0

**Task 3 — Different Kernels**

In [10]:
svm_linear = SVC(kernel='linear')

svm_linear.fit(X_train4, y_train4)

pred_linear = svm_linear.predict(X_test4)

acc_linear = accuracy_score(y_test4, pred_linear)

print("Linear Kernel Accuracy:", acc_linear)

Linear Kernel Accuracy: 1.0

**Polynomial Kernel**

In [11]:
svm_poly = SVC(kernel='poly')

svm_poly.fit(X_train4, y_train4)

pred_poly = svm_poly.predict(X_test4)

acc_poly = accuracy_score(y_test4, pred_poly)

print("Polynomial Kernel Accuracy:", acc_poly)

Polynomial Kernel Accuracy: 1.0

**RBF Kernel**

In [12]:
svm_rbf = SVC(kernel='rbf')

svm_rbf.fit(X_train4, y_train4)

pred_rbf = svm_rbf.predict(X_test4)

acc_rbf = accuracy_score(y_test4, pred_rbf)

print("RBF Kernel Accuracy:", acc_rbf)

RBF Kernel Accuracy: 1.0

**Task 4 — Compare Results**

In [13]:
print("Comparison of Models")

print("SVM with 2 Features:", acc2)
print("SVM with 4 Features:", acc4)

print("Linear Kernel:", acc_linear)
print("Polynomial Kernel:", acc_poly)
print("RBF Kernel:", acc_rbf)

Comparison of Models
SVM with 2 Features: 0.9
SVM with 4 Features: 1.0
Linear Kernel: 1.0
Polynomial Kernel: 1.0
RBF Kernel: 1.0